### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by zBugi** [treescale/treescale#10]
When will be the Website treescale.com available again, with the dashboard and so on ?
Just asking because its down or just showing see picture below since dec 2021.
![image](https://user-images.githubusercontent.com/64066508/153031719-e43b5d57-3fd4-400f-952e-63a60b149a1e.png)

**Comment by tigranbs** [comment]
@zBugi there have been a communication that Private Docker registry is going to be removed and service is moving to be an open source project. Docker container service have been shut down on December 21, 2020 and this repository doesn't have any relations to that service
