### ISSUE TITLE
treescale seems down

### ISSUE THREAD

**Issue by rafakwolf** [treescale/treescale#8]
frontend dash
![image](https://user-images.githubusercontent.com/2060578/84686052-a1147a00-af11-11ea-9187-55821527808a.png)
...and attempting to upload an image
![image](https://user-images.githubusercontent.com/2060578/84686091-b7bad100-af11-11ea-83d3-40fb8d72cdd9.png)

Thanks :)

**Comment by jo6r** [comment]
i have similar problem
![push](https://user-images.githubusercontent.com/48107393/96294636-f8744500-0fec-11eb-9d34-c867ea0a0539.png)
